name: Workflow Run
on:
  workflow_run:
    workflows: [CI Suite]
    types:
      - completed
jobs:
  workflow_run_test:
    name: Workflow Run Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read file
        run: cat ./README.md